// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "388373e4-6cba-406d-a4eb-2641a85c0127";

const char SSID[]               = "JeremyWhyFi?";    // Network SSID (name)
const char PASS[]               = "jeremy_21";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "sHAMAe9RF0S7bDh1v0Q?wyvIy";    // Secret device password

void onMuteSwitchChange();

CloudSwitch muteSwitch;
int light_level;
int sound_level;
CloudRelativeHumidity humid;
CloudTemperature temp;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(muteSwitch, READWRITE, ON_CHANGE, onMuteSwitchChange);
  ArduinoCloud.addProperty(light_level, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(sound_level, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humid, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temp, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
